name: Tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - "*"

jobs:
  linux:
    name: ${{ matrix.PLATFORM }} py${{ matrix.PYTHON_VERSION }}
    runs-on: ${{ matrix.PLATFORM }}
    strategy:
      fail-fast: false
      matrix:
        PLATFORM: ['ubuntu-latest', 'macos-latest',  'windows-latest']
        PYTHON_VERSION: ['3.6', '3.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ matrix.PYTHON_VERSION }}-pip-${{ hashFiles('requirements.txt', 'setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-py-${{ matrix.PYTHON_VERSION }}-pip-
      - name: Setup python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          architecture: 'x64'
      - name: Install python dependencies
        run: |
          pip install setuptools pip --upgrade --user
          pip install --upgrade .[cache] pytest-cov codecov
      - name: Show python environment
        run: |
          python --version
          python -m pip list
      - name: Run python tests
        # disable automatic inclusion for coverage
        run: |
          pytest -p no:check-links --cov pytest_check_links --cov-report term-missing
      - name: Upload coverage
        run: |
          codecov
