name: Tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - "*"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-build-${{ hashFiles('setup.cfg') }}
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Install build dependencies
        run: pip install --upgrade pip wheel setuptools
      - name: Build packages
        run: python setup.py sdist bdist_wheel
      - name: Calculate hashes
        run: |
          cd dist
          sha256sum * | tee SHA256SUMS
      - name: Archive packages
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  test:
    name: ${{ matrix.PLATFORM }} py${{ matrix.PYTHON_VERSION }}
    needs: build
    runs-on: ${{ matrix.PLATFORM }}
    strategy:
      fail-fast: false
      matrix:
        PLATFORM: ['ubuntu-latest', 'macos-latest',  'windows-latest']
        PYTHON_VERSION: ['3.6', '3.9', 'pypy3']
        exclude:
        - PLATFORM: windows-latest
          PYTHON_VERSION: pypy3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ matrix.PYTHON_VERSION }}-pip-${{ hashFiles('requirements.cfg', 'setup.cfg') }}
      - name: Setup python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          architecture: 'x64'
      - name: Install python dependencies
        run: |
          pip install setuptools pip wheel --upgrade --user
      - name: Download built artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Install built package
        run: |
          python -m pip install --upgrade --find-links dist pytest-check-links codecov pytest-cov requests-cache
      - name: Show python environment
        run: |
          python --version
          python -m pip list
          python -m pip check
      - name: Cache links
        uses: actions/cache@v1
        with:
          path: .pytest-check-links-cache.sqlite
          key: links
      - name: Smoke test
        run: |
          pytest --check-links --check-links-cache README.md
      - name: Run python tests
        # disable automatic inclusion for coverage
        run: |
          pytest -p no:check-links -vv --cov pytest_check_links --cov-report term-missing
      - name: Upload coverage
        run: |
          codecov
